apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

#transformers:
#  - image-tag-transformer.yaml

patches:
  - target:
      kind: Namespace
      name: ocm
    path: patches.yaml
