apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "OpenShift Cluster Management (OCM)"
  labels:
    openshift.io/cluster-monitoring: 'true'
    argocd.argoproj.io/managed-by: openshift-gitops
  name: ocm
